/**
 * Banata Auth component schema.
 *
 * Re-exports the schema from @banata-auth/convex.
 * This file would normally be auto-generated by:
 *   npx auth generate --config ./auth.ts --output ./schema.ts
 *
 * For now, we import the pre-defined schema from the package.
 */
export { default } from "@banata-auth/convex/schema";
